// Draws the launcher icons and the launch-screen mark for both flavors, so the
// PNGs in android/app/src/<flavor>/res are reproducible rather than mystery
// binaries. Nothing imports this: it is run by hand after the brand changes.
//
//   flutter test tool/generate_brand_assets.dart
//
// It paints the same lockup mark the apps wear in their app bar — a rounded
// square in the portal colour with an ExtraBold white "Ss" — using the bundled
// Inter, so the icon on the home screen and the "Ss" inside the app are the
// same drawing. Keep the colours below in step with
// lib/core/theme/app_colors.dart.
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

/// The one glyph the brand is built from.
const _mark = 'Ss';

/// AppColors.primary for the principal, AppColors.teal for the teacher. Two
/// apps from one codebase sit next to each other on a phone, and the label
/// under the icon is the only other thing telling them apart.
const _flavors = <String, Color>{'principal': Color(0xFF2456E6), 'teacher': Color(0xFF0D9488)};

/// Android density buckets, as a multiple of mdpi.
const _densities = <String, double>{'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4};

/// The legacy launcher icon is 48dp, the adaptive layers are drawn on a 108dp
/// canvas of which only the middle 66dp survives every mask, and the
/// launch-screen mark shows at 96dp.
const _legacyDp = 48.0;
const _adaptiveDp = 108.0;
const _splashDp = 96.0;

/// How much of each canvas the ink fills. The adaptive figure keeps the glyph
/// well inside the 61% safe zone; a circular mask cuts the corners off
/// anything larger.
const _legacyInkFraction = 0.52;
const _adaptiveInkFraction = 0.42;

/// Corner radius of the rounded square, as a fraction of its side.
const _cornerFraction = 0.22;

void main() {
  testWidgets('generate brand assets', (WidgetTester tester) async {
    // Every line below touches the real world - reading the font, encoding
    // images, writing files - and the test binding freezes the clock, so an
    // await outside runAsync never comes back.
    await tester.runAsync(() async {
      final root = Directory.current.path;
      await _loadInter(root);

      for (final entry in _flavors.entries) {
        final flavor = entry.key;
        final color = entry.value;
        final res = '$root/android/app/src/$flavor/res';

        for (final density in _densities.entries) {
          final scale = density.value;
          await _write(
            '$res/mipmap-${density.key}/ic_launcher.png',
            await _paint((_legacyDp * scale).round(), color: color, ground: true, ink: _legacyInkFraction),
          );
          await _write(
            '$res/drawable-${density.key}/ic_launcher_foreground.png',
            await _paint((_adaptiveDp * scale).round(), color: color, ground: false, ink: _adaptiveInkFraction),
          );
          await _write(
            '$res/drawable-${density.key}/ic_splash.png',
            await _paint((_splashDp * scale).round(), color: color, ground: true, ink: _legacyInkFraction),
          );
        }

        // The adaptive icon, with the same foreground as the monochrome layer so
        // Android 13 themed icons get the glyph rather than a filled square.
        await _writeText('$res/mipmap-anydpi-v26/ic_launcher.xml', _adaptiveIconXml);
        await _writeText('$res/values/ic_launcher_background.xml', _backgroundColorXml(color));

        // What a Play Store listing asks for: 512x512, square, and no rounding of
        // our own — the store applies its own mask.
        await _write(
          '$root/store/$flavor/icon-512.png',
          await _paint(512, color: color, ground: true, ink: _legacyInkFraction, corners: false),
        );
      }
    });
  });
}

const _adaptiveIconXml = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_brand_assets.dart -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
''';

String _backgroundColorXml(Color color) {
  final hex = color.toARGB32().toRadixString(16).substring(2).toUpperCase();
  return '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_brand_assets.dart -->
<resources>
    <color name="ic_launcher_background">#$hex</color>
</resources>
''';
}

/// The app bundles Inter; the test font is a row of boxes, so load the real one
/// off disk before painting anything.
Future<void> _loadInter(String root) async {
  final bytes = await File('$root/assets/fonts/Inter-ExtraBold.ttf').readAsBytes();
  final loader = FontLoader('Inter')..addFont(Future.value(ByteData.view(bytes.buffer)));
  await loader.load();
}

/// Paints the mark on a [size] by [size] canvas: the rounded square when
/// [ground] is set, otherwise the glyph alone on transparency for the adaptive
/// foreground. [ink] is the fraction of the canvas the glyph fills.
Future<Uint8List> _paint(
  int size, {
  required Color color,
  required bool ground,
  required double ink,
  bool corners = true,
}) async {
  final painter = TextPainter(
    text: TextSpan(
      text: _mark,
      style: TextStyle(
        // Drawn near its final scale, then trimmed to its ink below.
        fontSize: size * 0.6,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w800,
        color: Colors.white,
        height: 1,
      ),
    ),
    textDirection: TextDirection.ltr,
  )..layout();

  // The text box includes the ascent and descent the glyph does not fill, so
  // centring on it sits the mark visibly high. Centre on the inked pixels.
  final inked = await _inkBounds(painter);

  final recorder = ui.PictureRecorder();
  final canvas = Canvas(recorder);
  final side = size.toDouble();

  if (ground) {
    final rect = Rect.fromLTWH(0, 0, side, side);
    final paint = Paint()..color = color;
    if (corners) {
      canvas.drawRRect(RRect.fromRectAndRadius(rect, Radius.circular(side * _cornerFraction)), paint);
    } else {
      canvas.drawRect(rect, paint);
    }
  }

  final longest = inked.width > inked.height ? inked.width : inked.height;
  canvas.save();
  canvas.translate(side / 2, side / 2);
  canvas.scale((side * ink) / longest);
  canvas.translate(-inked.center.dx, -inked.center.dy);
  painter.paint(canvas, Offset.zero);
  canvas.restore();

  return _encode(recorder.endRecording(), size);
}

/// The bounding box of the pixels [painter] actually marks.
Future<Rect> _inkBounds(TextPainter painter) async {
  final width = painter.width.ceil();
  final height = painter.height.ceil();
  final recorder = ui.PictureRecorder();
  painter.paint(Canvas(recorder), Offset.zero);

  final image = await recorder.endRecording().toImage(width, height);
  final pixels = (await image.toByteData(format: ui.ImageByteFormat.rawRgba))!;
  image.dispose();

  var left = width, top = height, right = 0, bottom = 0;
  for (var y = 0; y < height; y++) {
    for (var x = 0; x < width; x++) {
      if (pixels.getUint8((y * width + x) * 4 + 3) > 8) {
        if (x < left) left = x;
        if (x > right) right = x;
        if (y < top) top = y;
        if (y > bottom) bottom = y;
      }
    }
  }
  if (right < left || bottom < top) throw StateError('The glyph inked nothing — is Inter loaded?');
  return Rect.fromLTRB(left.toDouble(), top.toDouble(), right + 1.0, bottom + 1.0);
}

Future<Uint8List> _encode(ui.Picture picture, int size) async {
  final image = await picture.toImage(size, size);
  final bytes = (await image.toByteData(format: ui.ImageByteFormat.png))!.buffer.asUint8List();
  image.dispose();
  return bytes;
}

Future<void> _write(String path, Uint8List bytes) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsBytes(bytes);
  // ignore: avoid_print
  print('wrote $path (${bytes.length} bytes)');
}

Future<void> _writeText(String path, String contents) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsString(contents);
  // ignore: avoid_print
  print('wrote $path');
}
