// Builds the launcher icons, the launch-screen mark, the Play Store icon and
// the in-app logo for both flavors from the web dashboard's logo, so the apps
// wear exactly the mark the web does. Nothing imports this: it is run by hand
// after the brand changes.
//
//   flutter test tool/generate_brand_assets.dart
//
// The source is frontend/public/logo-latest.png: a white interlocked "SS" on a
// blue square. The blue becomes the launcher background, and the white mark is
// lifted off it onto transparency for the adaptive icon's foreground layer.
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Relative to the mobile/ project, where the command is run.
const _source = '../frontend/public/logo-latest.png';

/// Both apps wear the web's logo. The label under the icon tells them apart.
const _flavors = ['principal', 'teacher'];

/// Android density buckets, as a multiple of mdpi.
const _densities = <String, double>{'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4};

/// The legacy launcher icon is 48dp, the adaptive layers are drawn on a 108dp
/// canvas of which only the middle 66dp survives every mask, and the
/// launch-screen mark shows at 96dp.
const _legacyDp = 48.0;
const _adaptiveDp = 108.0;
const _splashDp = 96.0;

/// How much of each canvas the mark fills. The adaptive figure keeps it well
/// inside the 61% safe zone; a circular mask cuts the corners off anything
/// larger. The legacy and splash marks sit on their own blue square.
const _legacyInkFraction = 0.5;
const _adaptiveInkFraction = 0.42;

/// Corner radius of the rounded square, as a fraction of its side.
const _cornerFraction = 0.22;

/// The in-app logo, shown at up to 40dp: 4x for the densest screens.
const _inAppSize = 160;

void main() {
  testWidgets('generate brand assets', (WidgetTester tester) async {
    // Every line below touches the real world - decoding, encoding, writing
    // files - and the test binding freezes the clock, so an await outside
    // runAsync never comes back.
    await tester.runAsync(() async {
      final root = Directory.current.path;
      final logo = await _decode(await File('$root/$_source').readAsBytes());
      final source = (await logo.toByteData(format: ui.ImageByteFormat.rawRgba))!;
      final ground = _pixel(source, logo.width, 4, 4);
      final mark = await _liftMark(source, logo.width, logo.height, ground);

      for (final flavor in _flavors) {
        final res = '$root/android/app/src/$flavor/res';

        for (final density in _densities.entries) {
          final scale = density.value;
          await _write(
            '$res/mipmap-${density.key}/ic_launcher.png',
            await _paint((_legacyDp * scale).round(), mark: mark, ground: ground, ink: _legacyInkFraction),
          );
          await _write(
            '$res/drawable-${density.key}/ic_launcher_foreground.png',
            await _paint((_adaptiveDp * scale).round(), mark: mark, ink: _adaptiveInkFraction),
          );
          await _write(
            '$res/drawable-${density.key}/ic_splash.png',
            await _paint((_splashDp * scale).round(), mark: mark, ground: ground, ink: _legacyInkFraction),
          );
        }

        // The adaptive icon, with the same foreground as the monochrome layer so
        // Android 13 themed icons get the mark rather than a filled square.
        await _writeText('$res/mipmap-anydpi-v26/ic_launcher.xml', _adaptiveIconXml);
        await _writeText('$res/values/ic_launcher_background.xml', _backgroundColorXml(ground));

        // What a Play Store listing asks for: 512x512, square, and no rounding of
        // our own — the store applies its own mask. It is the web logo as is.
        await _write('$root/store/$flavor/icon-512.png', await _scaled(logo, 512));
      }

      // The app bar and sign-in screen mark: the web logo itself.
      await _write('$root/assets/brand/logo.png', await _scaled(logo, _inAppSize));
    });
  });
}

const _adaptiveIconXml = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_brand_assets.dart -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
''';

String _backgroundColorXml(Color color) {
  final hex = color.toARGB32().toRadixString(16).substring(2).toUpperCase();
  return '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_brand_assets.dart -->
<resources>
    <color name="ic_launcher_background">#$hex</color>
</resources>
''';
}

Future<ui.Image> _decode(Uint8List bytes) async {
  final codec = await ui.instantiateImageCodec(bytes);
  return (await codec.getNextFrame()).image;
}

Color _pixel(ByteData pixels, int width, int x, int y) {
  final offset = (y * width + x) * 4;
  return Color.fromARGB(255, pixels.getUint8(offset), pixels.getUint8(offset + 1), pixels.getUint8(offset + 2));
}

/// The white mark on transparency, trimmed to its ink. Each pixel's opacity is
/// how far it sits from the blue ground towards white, so the anti-aliased
/// edges of the logo stay smooth.
Future<({ui.Image image, Rect bounds})> _liftMark(ByteData source, int width, int height, Color ground) async {
  final out = Uint8List(width * height * 4);
  final channels = [(ground.r * 255).round(), (ground.g * 255).round(), (ground.b * 255).round()];
  var left = width, top = height, right = 0, bottom = 0;

  for (var y = 0; y < height; y++) {
    for (var x = 0; x < width; x++) {
      final offset = (y * width + x) * 4;
      var whiteness = 1.0;
      for (var channel = 0; channel < 3; channel++) {
        final base = channels[channel];
        if (base >= 250) continue;
        final value = (source.getUint8(offset + channel) - base) / (255 - base);
        if (value < whiteness) whiteness = value;
      }
      final alpha = (whiteness.clamp(0.0, 1.0) * 255).round();
      out[offset] = 255;
      out[offset + 1] = 255;
      out[offset + 2] = 255;
      out[offset + 3] = alpha;
      if (alpha > 24) {
        if (x < left) left = x;
        if (x > right) right = x;
        if (y < top) top = y;
        if (y > bottom) bottom = y;
      }
    }
  }
  if (right < left || bottom < top) throw StateError('No white mark found in $_source');

  final image = await _fromPixels(out, width, height);
  return (image: image, bounds: Rect.fromLTRB(left.toDouble(), top.toDouble(), right + 1.0, bottom + 1.0));
}

Future<ui.Image> _fromPixels(Uint8List pixels, int width, int height) async {
  final buffer = await ui.ImmutableBuffer.fromUint8List(pixels);
  final descriptor = ui.ImageDescriptor.raw(buffer, width: width, height: height, pixelFormat: ui.PixelFormat.rgba8888);
  final codec = await descriptor.instantiateCodec();
  return (await codec.getNextFrame()).image;
}

/// The mark centred on a [size] by [size] canvas, on a rounded square of
/// [ground] when given, else on transparency. [ink] is the share of the canvas
/// the mark's longer side fills.
Future<Uint8List> _paint(int size, {required ({ui.Image image, Rect bounds}) mark, Color? ground, required double ink}) async {
  final recorder = ui.PictureRecorder();
  final canvas = Canvas(recorder);
  final side = size.toDouble();

  if (ground != null) {
    canvas.drawRRect(
      RRect.fromRectAndRadius(Rect.fromLTWH(0, 0, side, side), Radius.circular(side * _cornerFraction)),
      Paint()..color = ground,
    );
  }

  final bounds = mark.bounds;
  final longest = bounds.width > bounds.height ? bounds.width : bounds.height;
  final scale = (side * ink) / longest;
  final target = Rect.fromCenter(center: Offset(side / 2, side / 2), width: bounds.width * scale, height: bounds.height * scale);
  canvas.drawImageRect(mark.image, bounds, target, Paint()..filterQuality = FilterQuality.high);

  return _encode(recorder.endRecording(), size);
}

/// The whole logo, scaled to [size].
Future<Uint8List> _scaled(ui.Image logo, int size) async {
  final recorder = ui.PictureRecorder();
  Canvas(recorder).drawImageRect(
    logo,
    Rect.fromLTWH(0, 0, logo.width.toDouble(), logo.height.toDouble()),
    Rect.fromLTWH(0, 0, size.toDouble(), size.toDouble()),
    Paint()..filterQuality = FilterQuality.high,
  );
  return _encode(recorder.endRecording(), size);
}

Future<Uint8List> _encode(ui.Picture picture, int size) async {
  final image = await picture.toImage(size, size);
  final png = (await image.toByteData(format: ui.ImageByteFormat.png))!;
  image.dispose();
  return png.buffer.asUint8List();
}

Future<void> _write(String path, Uint8List bytes) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsBytes(bytes);
}

Future<void> _writeText(String path, String text) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsString(text);
}
