import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';

import '../../../core/api/api_exception.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/widgets/app_cards.dart';
import '../../../core/widgets/state_views.dart';
import '../data/principal_repository.dart';
import '../data/student_models.dart';

/// Add Student: the web create form's essential fields, with the same
/// required ones (name, class, gender, parent name and phone). Admission
/// number is generated by the server when left blank, as on the web.
/// Pops `true` once the student is saved.
class AddStudentScreen extends StatefulWidget {
  const AddStudentScreen({super.key});

  @override
  State<AddStudentScreen> createState() => _AddStudentScreenState();
}

class _AddStudentScreenState extends State<AddStudentScreen> {
  final _formKey = GlobalKey<FormState>();
  final _name = TextEditingController();
  final _admission = TextEditingController();
  final _roll = TextEditingController();
  final _parentName = TextEditingController();
  final _parentPhone = TextEditingController();
  final _address = TextEditingController();

  late Future<List<ClassChoice>> _classes;
  String? _classId;
  String? _gender;
  DateTime? _dateOfBirth;
  bool _saving = false;
  String? _error;

  static const _genders = [('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')];

  @override
  void initState() {
    super.initState();
    _classes = context.read<PrincipalRepository>().classes();
  }

  @override
  void dispose() {
    for (final controller in [_name, _admission, _roll, _parentName, _parentPhone, _address]) {
      controller.dispose();
    }
    super.dispose();
  }

  Future<void> _pickDateOfBirth() async {
    final now = DateTime.now();
    final picked = await showDatePicker(
      context: context,
      initialDate: _dateOfBirth ?? DateTime(now.year - 10, now.month, now.day),
      firstDate: DateTime(now.year - 25),
      lastDate: now,
    );
    if (picked != null) setState(() => _dateOfBirth = picked);
  }

  Future<void> _save() async {
    setState(() => _error = null);
    if (!(_formKey.currentState?.validate() ?? false)) return;

    setState(() => _saving = true);
    try {
      await context.read<PrincipalRepository>().createStudent(
            NewStudent(
              classId: _classId!,
              fullName: _name.text,
              parentName: _parentName.text,
              parentPhone: _parentPhone.text,
              admissionNumber: _admission.text,
              rollNumber: int.tryParse(_roll.text.trim()),
              gender: _gender,
              dateOfBirth: _dateOfBirth,
              address: _address.text,
            ),
          );
      if (mounted) Navigator.of(context).pop(true);
    } on ApiException catch (error) {
      if (mounted) setState(() => _error = error.message);
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Student')),
      body: FutureBuilder<List<ClassChoice>>(
        future: _classes,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) return const LoadingView();
          if (snapshot.hasError) {
            return ErrorView(
              message: snapshot.error is ApiException
                  ? (snapshot.error as ApiException).message
                  : 'Could not load classes.',
              onRetry: () => setState(() {
                _classes = context.read<PrincipalRepository>().classes();
              }),
            );
          }

          final classes = snapshot.data!;
          if (classes.isEmpty) {
            return const EmptyView(
              icon: Icons.class_rounded,
              title: 'No classes yet',
              message: 'Create a class in More → Classes & Sections before adding students.',
            );
          }

          return Form(
            key: _formKey,
            child: ListView(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 32),
              children: [
                const SectionHeader(title: 'Student'),
                TextFormField(
                  controller: _name,
                  textCapitalization: TextCapitalization.words,
                  decoration: const InputDecoration(labelText: 'Full name *'),
                  validator: (value) => (value?.trim().length ?? 0) < 2 ? 'Enter the student’s full name' : null,
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  initialValue: _classId,
                  isExpanded: true,
                  decoration: const InputDecoration(labelText: 'Class *'),
                  items: [
                    for (final item in classes) DropdownMenuItem(value: item.id, child: Text(item.label)),
                  ],
                  onChanged: (value) => setState(() => _classId = value),
                  validator: (value) => value == null ? 'Choose a class' : null,
                ),
                const SizedBox(height: 12),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: TextFormField(
                        controller: _admission,
                        decoration: const InputDecoration(
                          labelText: 'Admission no',
                          helperText: 'Auto if blank',
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: TextFormField(
                        controller: _roll,
                        keyboardType: TextInputType.number,
                        decoration: const InputDecoration(labelText: 'Roll no'),
                        validator: (value) {
                          final text = value?.trim() ?? '';
                          if (text.isEmpty) return null;
                          final number = int.tryParse(text);
                          return number == null || number < 1 ? 'Whole number' : null;
                        },
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  initialValue: _gender,
                  isExpanded: true,
                  decoration: const InputDecoration(labelText: 'Gender *'),
                  items: [
                    for (final (value, label) in _genders) DropdownMenuItem(value: value, child: Text(label)),
                  ],
                  onChanged: (value) => setState(() => _gender = value),
                  validator: (value) => value == null ? 'Choose a gender' : null,
                ),
                const SizedBox(height: 12),
                InkWell(
                  onTap: _pickDateOfBirth,
                  borderRadius: BorderRadius.circular(AppRadii.card),
                  child: InputDecorator(
                    decoration: const InputDecoration(
                      labelText: 'Date of birth',
                      suffixIcon: Icon(Icons.calendar_today_rounded, size: 18),
                    ),
                    child: Text(
                      _dateOfBirth == null ? 'Not set' : DateFormat('d MMM yyyy').format(_dateOfBirth!),
                      style: TextStyle(
                        color: _dateOfBirth == null ? AppColors.textMuted : AppColors.textPrimary,
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 22),
                const SectionHeader(title: 'Parent / Guardian'),
                TextFormField(
                  controller: _parentName,
                  textCapitalization: TextCapitalization.words,
                  decoration: const InputDecoration(labelText: 'Parent name *'),
                  validator: (value) => (value?.trim().length ?? 0) < 2 ? 'Enter the parent’s name' : null,
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _parentPhone,
                  keyboardType: TextInputType.phone,
                  maxLength: 10,
                  decoration: const InputDecoration(labelText: 'Parent phone *', counterText: ''),
                  validator: (value) =>
                      RegExp(r'^\d{10}$').hasMatch(value?.trim() ?? '') ? null : 'Enter a 10-digit phone number',
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _address,
                  maxLines: 2,
                  decoration: const InputDecoration(labelText: 'Address'),
                ),
                if (_error != null) ...[
                  const SizedBox(height: 14),
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: AppColors.dangerSoft,
                      borderRadius: BorderRadius.circular(AppRadii.card),
                    ),
                    child: Text(_error!, style: const TextStyle(color: AppColors.danger, fontWeight: FontWeight.w600)),
                  ),
                ],
                const SizedBox(height: 20),
                FilledButton(
                  onPressed: _saving ? null : _save,
                  child: Text(_saving ? 'Saving…' : 'Add Student'),
                ),
                const SizedBox(height: 10),
                const Text(
                  'Father, mother, fee structure, transport and documents can be added on the web dashboard.',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 12, color: AppColors.textSecondary),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
