import { Router } from "express";
import { academicYearsRouter } from "../modules/academicYears/academicYears.routes.js";
import { activityRouter } from "../modules/activity/activity.routes.js";
import { apiHealthHandler, dbHealthHandler } from "./health.js";
import { authRouter } from "../modules/auth/auth.routes.js";
import { attendanceRouter } from "../modules/attendance/attendance.routes.js";
import { classesRouter } from "../modules/classes/classes.routes.js";
import chatbotRouter from "../modules/chatbot/chatbot.routes.js";
import { communicationRouter } from "../modules/communication/communication.routes.js";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes.js";
import { demoRouter } from "../modules/demo/demo.routes.js";
import { feesRouter } from "../modules/fees/fees.routes.js";
import { homeworkRouter } from "../modules/homework/homework.routes.js";
import { marksRouter } from "../modules/marks/marks.routes.js";
import { analyticsRouter } from "../modules/analytics/analytics.routes.js";
import { notificationsRouter } from "../modules/notifications/notifications.routes.js";
import { onboardingRouter } from "../modules/onboarding/onboarding.routes.js";
import { reportsRouter } from "../modules/reports/reports.routes.js";
import { settingsRouter } from "../modules/settings/settings.routes.js";
import { studentsRouter } from "../modules/students/students.routes.js";
import { superAdminRouter } from "../modules/superAdmin/superAdmin.routes.js";
import { tenantSetupRouter } from "../modules/tenantSetup/tenantSetup.routes.js";
import { usersRouter } from "../modules/users/users.routes.js";
import { whatsappRouter } from "../modules/whatsapp/whatsapp.routes.js";
import { auditMutatingRequest } from "../middleware/activityAudit.js";

export const apiRouter = Router();

apiRouter.get("/health", apiHealthHandler);
apiRouter.get("/health/db", dbHealthHandler);
apiRouter.use("/onboarding", onboardingRouter);
apiRouter.use("/super-admin", superAdminRouter);
apiRouter.use("/tenant-setup", tenantSetupRouter);
apiRouter.use(auditMutatingRequest);

apiRouter.use("/auth", authRouter);
apiRouter.use("/academic-years", academicYearsRouter);
apiRouter.use("/activity-logs", activityRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/classes", classesRouter);
apiRouter.use("/chatbot", chatbotRouter);
apiRouter.use("/communication", communicationRouter);
apiRouter.use("/students", studentsRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/homework", homeworkRouter);
apiRouter.use("/marks", marksRouter);
apiRouter.use("/fees", feesRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/demo", demoRouter);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/wa", whatsappRouter);
