ALTER TYPE "CommunicationMessageType" ADD VALUE IF NOT EXISTS 'ABSENCE_NOTIFICATION';
ALTER TYPE "CommunicationMessageType" ADD VALUE IF NOT EXISTS 'FEE_REMINDER';
ALTER TYPE "CommunicationMessageType" ADD VALUE IF NOT EXISTS 'EXAM_ANNOUNCEMENT';
ALTER TYPE "CommunicationMessageType" ADD VALUE IF NOT EXISTS 'PTM_INVITE';
ALTER TYPE "CommunicationMessageType" ADD VALUE IF NOT EXISTS 'HOLIDAY_NOTICE';
ALTER TYPE "CommunicationMessageType" ADD VALUE IF NOT EXISTS 'GENERIC_NOTICE';
ALTER TYPE "CommunicationMessageType" ADD VALUE IF NOT EXISTS 'BIRTHDAY_WISH';
