import { sendError } from '../utils/response.js';

/**
 * Global Fastify error handler.
 *
 * - Logs the full error internally.
 * - Returns a safe, consistent JSON response to the client.
 * - Never leaks stack traces or Prisma internals in production.
 */
export function errorHandler(error, request, reply) {
  request.log.error(error);

  // Fastify validation errors (generated by schema / Zod)
  if (error.validation) {
    return sendError(reply, 400, 'Validation failed', error.validation);
  }

  // Mongoose validation errors
  if (error.name === 'ValidationError') {
    return sendError(reply, 400, 'Mongoose Validation failed', error.message);
  }

  // Mongoose duplicate key error
  if (error.code === 11000) {
    return sendError(reply, 409, 'Database consistency conflict (duplicate key)');
  }

  const statusCode = error.statusCode || 500;
  const isProd = process.env.NODE_ENV === 'production';

  const message =
    statusCode >= 500 && isProd
      ? 'Internal server error'
      : error.message || 'Something went wrong';

  return sendError(reply, statusCode, message);
}
